#! /bin/sh

### Execs ###
sxhkd &
pkill polybar
polybar taskbar &
polybar systembar &
pkill picom
picom &
nitrogen $HOME/Pictures/Wallpapers/emilia.png --set-zoom-fill
ibus-daemon -rdx

### Monitors ###
bspc monitor -d I II III IV V VI VII VIII IX X

### Border Config ###
bspc config border_width        1
bspc config window_gap          10
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding		40
bspc config bottom_padding	25

### Colors ###
bspc config active_border_color '#68c0c3'
bspc config normal_border_color '#b06fc2'
bspc config focused_border_color '#68c0c3'

### Rules ###
bspc rule -a google-chrome-stable  desktop='^1'
